#!/usr/bin/env bash
#
# Copy proving artefacts out of atrum-core into public/, where the harness can fetch them.
#
# WHY THIS IS A SCRIPT AND NOT A COMMITTED COPY
#
# Every artefact below is gitignored in atrum-core and regenerated by `make circuits`, and
# `snarkjs zkey contribute` is deliberately non-deterministic -- the randomness IS the
# security property. So a checked-in copy silently goes stale against the verifier it is
# supposed to match, and the failure surfaces as InvalidProof(), which looks exactly like a
# broken contract rather than a stale file.
#
# atrum-zk-poc/web/vendor/ was populated by a one-off `cp` in setup.sh with nothing recording
# what built it. This script is the reproducible version of that step: re-run it after every
# `make circuits` in atrum-core.
#
# Usage: ./scripts/sync-assets.sh          (defaults to ../atrum-core)
#        ATRUM_CORE=/path/to/core ./scripts/sync-assets.sh
set -euo pipefail

cd "$(dirname "$0")/.."

ATRUM_CORE="${ATRUM_CORE:-../atrum-core}"
BUILD="$ATRUM_CORE/circuits/build"

if [[ ! -d "$BUILD" ]]; then
    echo "error: no circuits/build at $BUILD" >&2
    echo "       set ATRUM_CORE, or run 'make circuits' in atrum-core first." >&2
    exit 1
fi

# The four live user actions. `bet` and `redeem` are the deprecated plaintext circuits and
# are deliberately absent -- a plaintext market has no redemption path at all now, so a
# client must never build one.
CIRCUITS=(deposit bet_encrypted redeem_private withdraw)

mkdir -p public/circuits public/fixtures public/vendor

available=()
missing=()

for c in "${CIRCUITS[@]}"; do
    wasm="$BUILD/${c}_js/${c}.wasm"
    zkey="$BUILD/${c}.zkey"
    vkey="$BUILD/${c}_vkey.json"

    # Missing is not fatal: redeem_private and withdraw have no artefacts until `make
    # circuits` has been run at least once, and the harness is useful before that.
    if [[ ! -f "$wasm" || ! -f "$zkey" ]]; then
        missing+=("$c")
        continue
    fi

    mkdir -p "public/circuits/$c"
    cp "$wasm" "public/circuits/$c/$c.wasm"
    cp "$zkey" "public/circuits/$c/$c.zkey"

    # The vkey is what lets the harness VERIFY the proof it just timed, not merely produce
    # one. A fast wrong proof is worse than a slow right one.
    if [[ -f "$vkey" ]]; then
        cp "$vkey" "public/circuits/$c/${c}_vkey.json"
    else
        echo "  warn: no $vkey -- harness will time $c but cannot verify it" >&2
    fi

    available+=("$c")
done

# Canned circuit inputs recorded by atrum-core's proving spike. Field names match each
# circuit's `component main {public [...]}` declaration exactly, so they feed fullProve
# with no renaming.
cp "$BUILD/witness-inputs.json" public/fixtures/witness-inputs.json

# snarkjs's own browser build, from THIS repo's node_modules -- version-pinned by
# package-lock.json rather than hand-vendored.
SNARKJS="node_modules/snarkjs/build/snarkjs.min.js"
if [[ ! -f "$SNARKJS" ]]; then
    echo "error: $SNARKJS not found -- run 'npm install' first." >&2
    exit 1
fi
cp "$SNARKJS" public/vendor/snarkjs.min.js

echo
echo "synced from $BUILD"
printf '  available : %s\n' "${available[*]:-none}"
if (( ${#missing[@]} )); then
    printf '  MISSING   : %s\n' "${missing[*]}"
    echo "              run 'make circuits' in atrum-core, then re-run this script."
fi

du -sh public/circuits 2>/dev/null | awk '{print "  total     : " $1 " of circuit artefacts"}'
