#!/usr/bin/env bash
#
# Copy proving artefacts out of atrum-core into public/, where the harness can fetch them.
#
# WHY THIS IS A SCRIPT AND NOT A COMMITTED COPY
#
# Every artefact below is gitignored in atrum-core and regenerated by `make circuits`, and
# `snarkjs zkey contribute` is deliberately non-deterministic -- the randomness IS the
# security property. So a checked-in copy silently goes stale against the verifier it is
# supposed to match, and the failure surfaces as InvalidProof(), which looks exactly like a
# broken contract rather than a stale file.
#
# atrum-zk-poc/web/vendor/ was populated by a one-off `cp` in setup.sh with nothing recording
# what built it. This script is the reproducible version of that step: re-run it after every
# `make circuits` in atrum-core.
#
# Usage: ./scripts/sync-assets.sh          (defaults to ../atrum-core)
#        ATRUM_CORE=/path/to/core ./scripts/sync-assets.sh
set -euo pipefail

cd "$(dirname "$0")/.."

ATRUM_CORE="${ATRUM_CORE:-../atrum-core}"
BUILD="$ATRUM_CORE/circuits/build"

if [[ ! -d "$BUILD" ]]; then
    echo "error: no circuits/build at $BUILD" >&2
    echo "       set ATRUM_CORE, or run 'make circuits' in atrum-core first." >&2
    exit 1
fi

# The four live user actions. `bet` and `redeem` are the deprecated plaintext circuits and
# are deliberately absent -- a plaintext market has no redemption path at all now, so a
# client must never build one.
CIRCUITS=(deposit bet_encrypted redeem_private withdraw)

mkdir -p public/circuits public/fixtures public/vendor

available=()
missing=()

for c in "${CIRCUITS[@]}"; do
    wasm="$BUILD/${c}_js/${c}.wasm"
    zkey="$BUILD/${c}.zkey"
    vkey="$BUILD/${c}_vkey.json"

    # Missing is not fatal: redeem_private and withdraw have no artefacts until `make
    # circuits` has been run at least once, and the harness is useful before that.
    if [[ ! -f "$wasm" || ! -f "$zkey" ]]; then
        missing+=("$c")
        continue
    fi

    mkdir -p "public/circuits/$c"
    cp "$wasm" "public/circuits/$c/$c.wasm"
    cp "$zkey" "public/circuits/$c/$c.zkey"

    # The vkey is what lets the harness VERIFY the proof it just timed, not merely produce
    # one. A fast wrong proof is worse than a slow right one.
    if [[ -f "$vkey" ]]; then
        cp "$vkey" "public/circuits/$c/${c}_vkey.json"
    else
        echo "  warn: no $vkey -- harness will time $c but cannot verify it" >&2
    fi

    available+=("$c")
done

# Canned circuit inputs recorded by atrum-core's proving spike. Field names match each
# circuit's `component main {public [...]}` declaration exactly, so they feed fullProve
# with no renaming.
cp "$BUILD/witness-inputs.json" public/fixtures/witness-inputs.json

# Node proving times, measured by `make bench` in atrum-core. The harness divides browser
# timings by these, so both halves of the multiplier come from the same machine. Optional:
# without it the harness falls back to HANDOFF's figures and says so.
if [[ -f "$BUILD/proving-baseline.json" ]]; then
    cp "$BUILD/proving-baseline.json" public/fixtures/proving-baseline.json
else
    echo "  note: no proving-baseline.json -- run 'make bench' in atrum-core" >&2
    rm -f public/fixtures/proving-baseline.json
fi

# atrum-core's note/commitment/packing/ElGamal primitives, bundled for the browser.
#
# WHY BUNDLE RATHER THAN REIMPLEMENT. `circuits/scripts/atrum.mjs` is already the third
# implementation of these hashing rules, alongside `note.circom` and
# `IncrementalMerkleTree.sol`, and all three must agree bit for bit. A fourth copy living in
# the frontend is how they would drift -- and a divergent commitment fails at proof
# verification with no diagnostic, which is the worst possible symptom.
#
# WHY BUNDLE RATHER THAN COPY. Those modules import `circomlibjs` and `js-sha3` as bare
# specifiers, which a no-bundler page cannot resolve. esbuild resolves them out of
# atrum-core's own node_modules and emits one self-contained ESM file.
ENTRY="$(mktemp -d)/entry.mjs"
CORE_ABS="$(cd "$ATRUM_CORE" && pwd)"
cat > "$ENTRY" <<EOF
export * from "$CORE_ABS/circuits/scripts/atrum.mjs";
export { buildElGamal, SUBGROUP_ORDER } from "$CORE_ABS/circuits/scripts/lib/elgamal.mjs";
EOF

# circomlibjs reaches for three Node builtins (`buffer`, `events`, `assert`) through its
# dependency tree. The aliases point them at the standard browser shims. verify-bundle.mjs
# below is what makes trusting those shims defensible -- it re-derives values the circuits
# already accepted and refuses the bundle if any differ.
npx --no-install esbuild "$ENTRY" \
    --bundle --format=esm --platform=browser \
    --alias:buffer=buffer --alias:events=events --alias:assert=assert \
    --define:global=globalThis \
    --inject:scripts/browser-shims.mjs \
    --outfile=public/vendor/atrum-core.mjs \
    --log-level=warning
rm -rf "$(dirname "$ENTRY")"

echo
echo "verifying the bundle against circuit-accepted values"
node scripts/verify-bundle.mjs

# snarkjs's own browser build, from THIS repo's node_modules -- version-pinned by
# package-lock.json rather than hand-vendored.
SNARKJS="node_modules/snarkjs/build/snarkjs.min.js"
if [[ ! -f "$SNARKJS" ]]; then
    echo "error: $SNARKJS not found -- run 'npm install' first." >&2
    exit 1
fi
cp "$SNARKJS" public/vendor/snarkjs.min.js

echo
echo "synced from $BUILD"
printf '  available : %s\n' "${available[*]:-none}"
if (( ${#missing[@]} )); then
    printf '  MISSING   : %s\n' "${missing[*]}"
    echo "              run 'make circuits' in atrum-core, then re-run this script."
fi

du -sh public/circuits 2>/dev/null | awk '{print "  total     : " $1 " of circuit artefacts"}'
